# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20150615_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[(b'need', b'Need'), (b'offer', b'Offer')], db_index=True, max_length=5)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_id', models.CharField(blank=True, max_length=64)),
                ('subject', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[(b'open', b'Open'), (b'solved', b'Solved'), (b'closed-without-solution', b'Closed without solution'), (b'draft', b'Draft')], default=b'open', max_length=32)),
                ('type_of', models.CharField(blank=True, choices=[(b'official', b'Official'), (b'informal', b'Informal')], max_length=10)),
                ('resources', models.TextField(blank=True)),
                ('need_urgent', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=64)),
                ('institution', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True)),
                ('info', models.TextField(blank=True, verbose_name=b'Additional contact details')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('handle', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('sort_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('sort_id',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to=b'documents')),
            ],
        ),
        migrations.CreateModel(
            name='FlisTopic',
            fields=[
                ('handle', models.SlugField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('sort_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('sort_id',),
            },
        ),
        migrations.AddField(
            model_name='catalogue',
            name='categories',
            field=models.ManyToManyField(to='live_catalogue.Category'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Country'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='documents',
            field=models.ManyToManyField(blank=True, to='live_catalogue.Document'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='flis_topics',
            field=models.ManyToManyField(to='live_catalogue.FlisTopic'),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='themes',
            field=models.ManyToManyField(blank=True, to='common.EnvironmentalTheme', verbose_name=b'Topics'),
        ),
    ]
